# Animations

animations {
    enabled = false

    animation = windows, 1, 7, default
    animation = fade, 0
    animation = border, 0
    animation = borderangle, 0
    animation = workspaces, 0
}

